### ISSUE TITLE
Blockchainification of poketransfers

### ISSUE THREAD

**Issue by patricklanger** [cbrgm/introduction-to-adrs#1]
# Title Blockchainification of poketransfers

Date: 2022-11-07, Author: Mathias Wanzenberg, Patrick Langer

## Status

- [x] - Proposed
- [ ] - Accepted
- [ ] - Rejected
- [ ] - Deprecated
- [ ] - Superseded

## Context

Funktionalität des Spiels muss Kundenwünschen angepasst werden, daher soll der Transfer von Pokémon unter Spielern nachvollzogen werden können.

## Considered Options
- Blockchain
- NoSql-Datenbank
- bestehende Datenbank erweitern

## Decision

Wir führen zusätzlich zum vorhandenen System eine Blockchain ein, um Transaktionen von Pokémon zwischen Spielen festzuhalten.

## Consequences

- Bestehende Funktionen müssen nicht verändert werden.
- Zum normalen Abspeichern der Transaktion, muss der Transfer in der Blockchain festgehalten werden.
- Konsistenz der Daten zwischen Blockchain und bestehender Datenbanklösung.

- API muss erweitert werden, um Funktionalität anzubieten.

**Comment by cbrgm** [comment]
Thanks!
