### ISSUE TITLE
Setup new Requestresponse and structure

### ISSUE THREAD

**Issue by Garry1704** [cbrgm/introduction-to-adrs#2]
# Send whole Pokemoninfos to user

Date: 2022-11-07, Author: Sebastian G.

## Status

- [x] - Proposed
- [ ] - Accepted
- [ ] - Rejected
- [ ] - Deprecated
- [ ] - Superseded

## Context

We need more informations about a pokemon in one request to minimize the traffic in our system. In the old system we get requests for every statfamily of a pokemon and have to list the available stats in a seperate request, e.g. attack stats, defense stats, special attacks etc...
Now we have more bandwith and want to minimize the requests to our system.

## Decision

We decided to send the whole entry and stats we got from one pokemon. For this Decision we changed the API version to v2, so the old api still exists and is downward compatible.

## Consequences

As a result for this decision we have to operate two systems simultanious. this means in the beginning of the api v2 we have a bit more work to do, but after the roll-out the the time to maintain is nearly the same. 
After the time of 6 month we have to cut off the old system and force the users to use the new system. 
**When the cut off of V1 is done we have reduced our traffic by more than 60%.**
The risk we have after this decision is, users dont want to use our api anymore. This risk is moderate, because we are the biggest system in this market and have the best datasets of pokemon.

**Comment by cbrgm** [comment]
Thanks! 😄
